#ifndef SAPPHIRE_DEFINITIONS_H
#define SAPPHIRE_DEFINITIONS_H

#define PAGE_SIZE 4096

#define DATABASE_COLUMN_NAME_MAX_SIZE 16
#define DATABASE_TABLE_NAME_MAX_SIZE 16

#endif //SAPPHIRE_DEFINITIONS_H