#ifndef SAPPHIRE_DB_FILE_FORMAT_H
#define SAPPHIRE_DB_FILE_FORMAT_H

// Lengths for identifiers
#define DATABASE_TABLE_IDENTIFIER_LENGTH 8
#define DATABASE_COLUMN_IDENTIFIER_LENGTH 8

// Database file format (page 0)
#define DB_HEADER_MAGIC_OFFSET 0
#define DB_HEADER_MAGIC_STRING "DBJF"
#define DB_HEADER_MAGIC_SIZE 4
#define DB_HEADER_VERSION_OFFSET (DB_HEADER_MAGIC_OFFSET + DB_HEADER_MAGIC_SIZE)
#define DB_HEADER_VERSION_SIZE 4
#define DB_HEADER_PAGE_SIZE_OFFSET (DB_HEADER_VERSION_OFFSET + DB_HEADER_VERSION_SIZE)
#define DB_HEADER_PAGE_SIZE_SIZE 4
#define DB_HEADER_NUM_TABLES_OFFSET (DB_HEADER_PAGE_SIZE_OFFSET + DB_HEADER_PAGE_SIZE_SIZE)
#define DB_HEADER_NUM_TABLES_SIZE 4

#define DB_TABLES_OFFSET (DB_HEADER_NUM_TABLES_OFFSET + DB_HEADER_NUM_TABLES_SIZE)
#define DB_TABLES_LENGTH_OFFSET 0
#define DB_TABLES_LENGTH_SIZE 4
#define DB_TABLES_ROOT_PAGE_OFFSET (DB_TABLES_LENGTH_OFFSET + DB_TABLES_LENGTH_SIZE)
#define DB_TABLES_ROOT_PAGE_SIZE 4
#define DB_TABLES_IDENTIFIER_OFFSET (DB_TABLES_ROOT_PAGE_OFFSET + DB_TABLES_ROOT_PAGE_SIZE)
#define DB_TABLES_IDENTIFIER_MAX_LENGTH DATABASE_TABLE_IDENTIFIER_LENGTH
#define DB_TABLES_NUM_COLUMNS_OFFSET (DB_TABLES_IDENTIFIER_OFFSET + DB_TABLES_IDENTIFIER_MAX_LENGTH)
#define DB_TABLES_NUM_COLUMNS_SIZE 4

#define DB_COLUMNS_OFFSET (DB_TABLES_NUM_COLUMNS_OFFSET + DB_TABLES_NUM_COLUMNS_SIZE)
#define DB_COLUMN_TYPE_OFFSET 0
#define DB_COLUMN_TYPE_SIZE 1
#define DB_COLUMN_CONSTRAINT_OFFSET (DB_COLUMN_TYPE_OFFSET + DB_COLUMN_TYPE_SIZE)
#define DB_COLUMN_CONSTRAINT_SIZE 1
#define DB_COLUMN_IDENTIFIER_OFFSET (DB_COLUMN_CONSTRAINT_OFFSET + DB_COLUMN_CONSTRAINT_SIZE)
#define DB_COLUMN_IDENTIFIER_MAX_LENGTH DATABASE_COLUMN_IDENTIFIER_LENGTH
#define DB_COLUMN_SIZE (DB_COLUMN_IDENTIFIER_OFFSET + DB_COLUMN_IDENTIFIER_MAX_LENGTH)

#endif //SAPPHIRE_DB_FILE_FORMAT_H
